import './globals.css'
import { Montserrat } from 'next/font/google'

const inter = Montserrat({
  weight: ['600', '700', '400', '800'],
  subsets: ['latin'], 
  variable: '--font-inter'
 })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-100 ${inter.className}`}>{children}</body>
    </html>
  )
}
